global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "api-gateway"
    static_configs:
      - targets: ["api-gateway:8000"]
    metrics_path: "/metrics"

  - job_name: "market-simulator"
    static_configs:
      - targets: ["market-simulator:8001"]
    metrics_path: "/metrics"

  - job_name: "ai-engine"
    static_configs:
      - targets: ["ai-engine:8002"]
    metrics_path: "/metrics"

  - job_name: "data-pipeline"
    static_configs:
      - targets: ["data-pipeline:8003"]
    metrics_path: "/metrics"

  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]
    metrics_path: "/metrics"

  - job_name: "influxdb"
    static_configs:
      - targets: ["influxdb:8086"]
    metrics_path: "/metrics" 