version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  api-gateway:
    build: ./services/api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  market-simulator:
    build: ./services/market-simulator
    ports:
      - "8001:8001"

  ai-engine:
    build: ./services/ai-engine
    ports:
      - "8002:8002"

  data-pipeline:
    build: ./services/data-pipeline
    ports:
      - "8003:8003"

  dashboard:
    build: ./dashboard
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"

networks:
  frontend:
  backend:
  monitoring:

volumes:
  postgres_data: